src/wellsfargo/models.py
from decimal import Decimal
from django.conf import settings
from django.contrib.auth.models import Group
from django.core import signing, exceptions
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import cached_property
from oscar.core.loading import get_model, get_class
from oscar.models.fields import PhoneNumberField
from .core.constants import (
    CREDIT_APP_STATUSES,
    TRANS_TYPE_AUTH,
    TRANS_TYPES,
    TRANS_STATUSES,
    INQUIRY_STATUSES,
    EN_US,
    PREQUAL_LOCALE_CHOICES,
    ENTRY_POINT_WEB,
    ENTRY_POINT_CHOICES,
    PREQUAL_TRANS_STATUS_APPROVED,
    PREQUAL_TRANS_STATUS_REJECTED,
    PREQUAL_TRANS_STATUS_CHOICES,
    PREQUAL_CUSTOMER_RESP_NONE,
    PREQUAL_CUSTOMER_RESP_CHOICES,
    get_prequal_trans_status_name,
)
from .core.applications import (
    USCreditAppMixin,
    BaseCreditAppMixin,
    USJointCreditAppMixin,
    BaseJointCreditAppMixin,
    CACreditAppMixin,
    CAJointCreditAppMixin,
)
from .core.fields import USStateField, USZipCodeField
from .security import encrypt_account_number, decrypt_account_number
import logging
import uuid
import urllib.parse

Benefit = get_model('offer', 'Benefit')
HiddenPostOrderAction = get_class('offer.results', 'HiddenPostOrderAction')

logger = logging.getLogger(__name__)


def _max_len(choices):
    """Given a list of char field choices, return the field max length"""
    lengths = [len(choice) for choice, _ in choices]
    return max(lengths)



class APICredentials(models.Model):
    name = models.CharField(_('Merchant Name'), max_length=200, default='Default')
    username = models.CharField(_('WFRS API Username'), max_length=200)
    password = models.CharField(_('WFRS API Password'), max_length=200)
    merchant_num = models.CharField(_('WFRS API Merchant Number'), max_length=200)
    user_group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.CASCADE)
    priority = models.IntegerField(_('Priority Order'), default=1)

    class Meta:
        ordering = ('-priority', '-id')
        verbose_name = _('API Credentials')
        verbose_name_plural = _('API Credentials')


    @classmethod
    def get_credentials(cls, user=None):
        if user and user.is_authenticated:
            creds = cls.objects.filter(user_group__in=user.groups.all()).first()
            if creds:
                return creds
        creds = cls.objects.filter(user_group=None).first()
        if creds:
            return creds
        logger.error('Application requested WFRS API Credentials for use by user {}, but none exist in the database for them.'.format(user))
        return cls()


    def __str__(self):
        return "%s:xxxx@wfrs/%s" % (self.username, self.merchant_num)



class FinancingPlan(models.Model):
    """
    An individual WFRS plan number and related metadata about it
    """
    plan_number = models.PositiveIntegerField(_("Plan Number"), unique=True, validators=[
        MinValueValidator(1001),
        MaxValueValidator(9999),
    ])
    description = models.TextField(_("Description"), blank=True, default='')
    fine_print_superscript = models.CharField(_("Fine Print Superscript"), blank=True, default='', max_length=10)
    apr = models.DecimalField(_("Annual percentage rate (0.0 – 100.0)"), max_digits=5, decimal_places=2, default='0.00', validators=[
        MinValueValidator(Decimal('0.00')),
        MaxValueValidator(Decimal('100.00')),
    ])
    term_months = models.PositiveSmallIntegerField(_("Term Length (months)"), default=12)
    product_price_threshold = models.DecimalField(_("Minimum Product Price for Plan Availability Advertising"),
        decimal_places=2,
        max_digits=12,
        default='0.00',
        validators=[MinValueValidator(Decimal('0.00'))])
    advertising_enabled = models.BooleanField(_("Is Advertising Enabled for Plan?"), default=False)
    is_default_plan = models.BooleanField(_("Is Default Plan?"), default=False)
    allow_credit_application = models.BooleanField(_('Allow new credit applications when user is eligible for this plan?'), default=True)

    class Meta:
        ordering = ('plan_number', )


    @classmethod
    def get_advertisable_plan_by_price(cls, price):
        plan = cls.objects\
            .exclude(term_months=0)\
            .filter(advertising_enabled=True)\
            .filter(product_price_threshold__gte='0.00')\
            .filter(product_price_threshold__lte=price)\
            .order_by('-product_price_threshold', '-apr')\
            .first()
        return plan


    def __str__(self):
        return "%s (plan number %s)" % (self.description, self.plan_number)

    def save(self, *args, **kwargs):
        if self.is_default_plan:
            self.__class__._default_manager.filter(is_default_plan=True).update(is_default_plan=False)
        super().save(*args, **kwargs)



class FinancingPlanBenefit(Benefit):
    """
    A group of WFRS plan numbers made available to a customer as the applied benefit of an offer or voucher. This
    makes it possible to offer different plan numbers to different customers based on any of the normal offer conditions.
    """
    group_name = models.CharField(_('Name'), max_length=200)
    plans = models.ManyToManyField(FinancingPlan)

    class Meta(Benefit.Meta):
        app_label = 'wellsfargo'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.proxy_class = '%s.%s' % (self.__class__.__module__, self.__class__.__name__)

    def __str__(self):
        return self.group_name

    def apply(self, basket, condition, offer):
        condition.consume_items(offer, basket, [])
        return HiddenPostOrderAction("Financing is available for your order")

    def apply_deferred(self, basket, order, application):
        return "Financing was available for your order: %s" % self.group_name

    @property
    def name(self):
        return self.group_name

    @property
    def description(self):
        nums = ', '.join([str(p.plan_number) for p in self.plans.all()])
        return "Causes the following Wells Fargo financing plans to be available: %s" % nums

    def _clean(self):
        group_name = getattr(self, 'group_name', None)
        if not group_name:
            raise exceptions.ValidationError(_((
                "Wells Fargo Financing Plan Benefit must have a group name. "
                "Use the Financing > Wells Fargo Plan Group dashboard to create this type of benefit."
            )))



class FraudScreenResult(models.Model):
    DECISION_REJECT = 'REJECT'
    DECISION_ACCEPT = 'ACCEPT'
    DECISION_ERROR = 'ERROR'
    DECISION_REVIEW = 'REVIEW'

    screen_type = models.CharField(_("Fraud Screen Type"), max_length=25)
    order = models.ForeignKey('order.Order', related_name='wfrs_fraud_screen_results', on_delete=models.CASCADE)
    reference = models.CharField(_("Reference"), max_length=128)
    decision = models.CharField(_("Decision"), max_length=25, choices=(
        (DECISION_REJECT, _("Transaction was rejected")),
        (DECISION_ACCEPT, _("Transaction was accepted")),
        (DECISION_ERROR, _("Error occurred while running fraud screen")),
        (DECISION_REVIEW, _("Transaction was flagged for manual review")),
    ))
    message = models.TextField(_("Message"))
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_datetime', '-id')


    def __str__(self):
        return self.message



class AccountNumberMixin(models.Model):
    last4_account_number = models.CharField(_("Last 4 digits of account number"), max_length=4)
    encrypted_account_number = models.BinaryField(null=True)

    class Meta:
        abstract = True

    @property
    def masked_account_number(self):
        return 'xxxxxxxxxxxx{}'.format(self.last4_account_number or 'xxxx')

    @property
    def account_number(self):
        acct_num = None
        if self.encrypted_account_number:
            acct_num = decrypt_account_number(self.encrypted_account_number)
        if not acct_num:
            acct_num = self.masked_account_number
        return acct_num

    @account_number.setter
    def account_number(self, value):
        if len(value) != 16:
            raise ValueError('Account number must be 16 digits long')
        self.last4_account_number = value[-4:]
        self.encrypted_account_number = encrypt_account_number(value)

    def purge_encrypted_account_number(self):
        self.encrypted_account_number = None
        self.save()



class AccountInquiryResult(AccountNumberMixin, models.Model):
    credit_app_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    credit_app_id = models.PositiveIntegerField(null=True, blank=True)
    credit_app_source = GenericForeignKey('credit_app_type', 'credit_app_id')

    prequal_response_source = models.ForeignKey('wellsfargo.PreQualificationResponse',
        verbose_name=_("Pre-Qualification Source"),
        related_name='account_inquiries',
        null=True, blank=True,
        on_delete=models.SET_NULL)

    status = models.CharField(_("Status"), choices=INQUIRY_STATUSES, max_length=2)

    first_name = models.CharField(_("First Name"), max_length=50)
    middle_initial = models.CharField(_("Middle Initial"), null=True, blank=True, max_length=1)
    last_name = models.CharField(_("Last Name"), max_length=50)
    phone_number = PhoneNumberField(_("Phone Number"))
    address = models.CharField(_("Address Line 1"), max_length=100)

    credit_limit = models.DecimalField(_("Account Credit Limit"), decimal_places=2, max_digits=12)

src/wellsfargo/dashboard/app.py
from django.conf.urls import url
from oscar.core.application import Application

from .views import (
    ApplicationSelectionView,
    CreditApplicationView,
    FinancingPlanListView,
    FinancingPlanCreateView,
    FinancingPlanUpdateView,
    FinancingPlanDeleteView,
    FinancingPlanBenefitListView,
    FinancingPlanBenefitCreateView,
    FinancingPlanBenefitUpdateView,
    FinancingPlanBenefitDeleteView,
    CreditApplicationListView,
    CreditApplicationDetailView,
    TransferMetadataListView,
    TransferMetadataDetailView,
    PreQualificationListView,
    PreQualificationDetailView,
)


class WFRSDashboardApplication(Application):
    name = None
    default_permissions = ['is_staff', ]

    apply_step1 = ApplicationSelectionView
    apply_step2 = CreditApplicationView
    plan_list = FinancingPlanListView
    plan_create = FinancingPlanCreateView
    plan_update = FinancingPlanUpdateView
    plan_delete = FinancingPlanDeleteView
    benefit_list = FinancingPlanBenefitListView
    benefit_create = FinancingPlanBenefitCreateView
    benefit_update = FinancingPlanBenefitUpdateView
    benefit_delete = FinancingPlanBenefitDeleteView
    application_list = CreditApplicationListView
    application_detail = CreditApplicationDetailView
    transfer_list = TransferMetadataListView
    transfer_detail = TransferMetadataDetailView
    prequal_list = PreQualificationListView
    prequal_detail = PreQualificationDetailView

    def get_urls(self):
        urlpatterns = [
            url(r'^apply/$',
                self.apply_step1.as_view(),
                name='wfrs-apply-step1'),
            url(r'^apply/(?P<region>\w+)/(?P<language>\w+)/(?P<app_type>\w+)/$',
                self.apply_step2.as_view(),
                name='wfrs-apply-step2'),

            url(r'^plans/$',
                self.plan_list.as_view(),
                name='wfrs-plan-list'),
            url(r'^plans/new/$',
                self.plan_create.as_view(),
                name='wfrs-plan-create'),
            url(r'^plans/(?P<pk>[0-9]+)/edit/$',
                self.plan_update.as_view(),
                name='wfrs-plan-edit'),
            url(r'^plans/(?P<pk>[0-9]+)/delete/$',
                self.plan_delete.as_view(),
                name='wfrs-plan-delete'),

            url(r'^benefits/$',
                self.benefit_list.as_view(),
                name='wfrs-benefit-list'),
            url(r'^benefits/new/$',
                self.benefit_create.as_view(),
                name='wfrs-benefit-create'),
            url(r'^benefits/(?P<pk>[0-9]+)/edit/$',
                self.benefit_update.as_view(),
                name='wfrs-benefit-edit'),
            url(r'^benefits/(?P<pk>[0-9]+)/delete/$',
                self.benefit_delete.as_view(),
                name='wfrs-benefit-delete'),

            url(r'^applications/$',
                self.application_list.as_view(),
                name='wfrs-application-list'),
            url(r'^applications/(?P<app_type>[a-z\-]+)/(?P<pk>[0-9]+)/$',
                self.application_detail.as_view(),
                name='wfrs-application-detail'),


            url(r'^transfers/$',
                self.transfer_list.as_view(),
                name='wfrs-transfer-list'),
            url(r'^transfers/(?P<merchant_reference>[A-Za-z0-9\-]+)/$',
                self.transfer_detail.as_view(),
                name='wfrs-transfer-detail'),

            url(r'^prequal-requests/$',
                self.prequal_list.as_view(),
                name='wfrs-prequal-list'),
            url(r'^prequal-requests/(?P<uuid>[A-Za-z0-9\-]+)/$',
                self.prequal_detail.as_view(),
                name='wfrs-prequal-detail'),
        ]
        return self.post_process_urls(urlpatterns)


application = WFRSDashboardApplication()

src/wellsfargo/templates/wfrs/dashboard/_application_row_actions.html
{% spaceless %}
    {% load i18n %}
    <a href="{% url 'wfrs-application-detail' app_type=record.APP_TYPE_CODE pk=record.pk %}" class="btn btn-primary">{% trans "View" %}</a>
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/_application_row_order_delay.html
{% spaceless %}
    {% load wfrs_filters %}
    {% if record.order_placed %}
        <span title="Order placed on {{ record.order_placed | localizedatetime }}, {{ record.created_datetime | timesince:record.order_placed }} after initial credit application.">
            {{ record.order_placed | timesinceminutes:record.created_datetime }}
        </span>
    {% else %}
        —
    {% endif %}
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/_application_row_secondary_applicant_name.html
{% spaceless %}
    {% if record.joint_last_name %}
        {{ record.joint_last_name }}, {{ record.joint_first_name }}
    {% else %}
        —
    {% endif %}
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/_application_row_submitting_user.html
{% spaceless %}
    {% if record.submitting_user_username and record.submitting_user_id %}
        <a href="{% url 'dashboard:user-detail' pk=record.submitting_user_id %}">{{ record.submitting_user_full_name | default:record.submitting_user_username }}</a>
    {% else %}
        —
    {% endif %}
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/_prequal_row_credit_limit.html
{% spaceless %}
    {% load currency_filters %}
    {{ record.response_credit_limit | currency | default:'—' }}
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/_prequal_row_order_delay.html
{% spaceless %}
    {% load wfrs_filters %}
    {% if record.order_date_placed %}
        <span title="Order placed on {{ record.order_date_placed | localizedatetime }}, {{ record.created_datetime | timesince:record.order_date_placed }} after initial credit application.">
            {{ record.order_date_placed | timesinceminutes:record.created_datetime }}
        </span>
    {% else %}
        —
    {% endif %}
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/_transfer_row_order.html
{% spaceless %}
    {% if record.order_number %}
        <a href="{% url 'dashboard:order-detail' number=record.order_number %}">{{ record.order_number }}</a>
    {% else %}
        —
    {% endif %}
{% endspaceless %}

src/wellsfargo/templates/wfrs/dashboard/application_detail.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load currency_filters %}
{% load wfrs_filters %}

{% block title %}
    {% trans "Credit Application Details" %} |
    {% trans "Wells Fargo" %} |
    {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'wfrs-application-list' %}?app_type={{ object.APP_TYPE_CODE }}">{% trans "Credit Applications" %}</a>
        </li>
        <li class="active">{% trans "Credit Application Details" %}</li>
    </ul>
{% endblock %}

{% block headertext %}
    {% trans "Credit Application Details" %}
{% endblock %}

{% block dashboard_content %}
    <div class="row">
        <div class="col-md-12">
            <div class="table-header">
                <h2>{% trans "General" %}</h2>
            </div>
            <table class="table table-bordered">
                <tr>
                    <td>{% trans "Email Address" %}</td>
                    <td>{{ object.email | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Resulting Account Number" %}</td>
                    <td>{{ object.account_number | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Requested Value" %}</td>
                    <td>{{ object.purchase_price | currency | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "IP Address" %}</td>
                    <td>{{ object.ip_address | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Created Date" %}</td>
                    <td>{{ object.created_datetime | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Modified Date" %}</td>
                    <td>{{ object.modified_datetime | default:"-" }}</td>
                </tr>
            </table>
        </div>

        <div class="col-md-6">
            <div class="table-header">
                <h2>{% trans "Main Applicant" %}</h2>
            </div>
            <table class="table table-bordered">
                <tr>
                    <th colspan="2">{% trans "Name" %}</th>
                </tr>
                <tr>
                    <td>{% trans "First Name" %}</td>
                    <td>{{ object.main_first_name | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Last Name" %}</td>
                    <td>{{ object.main_last_name | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Middle Initial" %}</td>
                    <td>{{ object.main_middle_initial | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Social Security Number / Social Insurance Number" %}</td>
                    <td>{{ object.main_ssn | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Address" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Line 1" %}</td>
                    <td>{{ object.main_address_line1 | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Line 2" %}</td>
                    <td>{{ object.main_address_line2 | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "City" %}</td>
                    <td>{{ object.main_address_city | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "State" %}</td>
                    <td>{{ object.main_address_state | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Postal Code" %}</td>
                    <td>{{ object.main_address_postcode | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Contact" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Home Phone" %}</td>
                    <td>{{ object.main_home_phone | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Cell Phone" %}</td>
                    <td>{{ object.main_cell_phone | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Residence" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Home Value" %}</td>
                    <td>{{ object.main_home_value | currency | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Mortgage Balance" %}</td>
                    <td>{{ object.main_mortgage_balance | currency | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Time at Address" %}</td>
                    <td>{{ object.main_time_at_address | timeat }}</td>
                </tr>
                <tr>
                    <td>{% trans "Housing Status" %}</td>
                    <td>{{ object.main_housing_status | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Employment" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Occupation" %}</td>
                    <td>{{ object.main_occupation | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Annual Income" %}</td>
                    <td>{{ object.main_annual_income | currency | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Employer Name" %}</td>
                    <td>{{ object.main_employer_name | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Time at Employer" %}</td>
                    <td>{{ object.main_time_at_employer | timeat }}</td>
                </tr>
                <tr>
                    <td>{% trans "Employer Phone" %}</td>
                    <td>{{ object.main_employer_phone | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Photo ID" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Photo ID Type" %}</td>
                    <td>{{ object.main_photo_id_type | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Photo ID Number" %}</td>
                    <td>{{ object.main_photo_id_number | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Driver's License Province" %}</td>
                    <td>{{ object.main_drivers_license_province | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Photo ID Expiration Date" %}</td>
                    <td>{{ object.main_photo_id_expiration | default:"-" }}</td>
                </tr>
            </table>
        </div>


        <div class="col-md-6">
            <div class="table-header">
                <h2>{% trans "Secondary Applicant" %}</h2>
            </div>
            <table class="table table-bordered">
                <tr>
                    <th colspan="2">{% trans "Name" %}</th>
                </tr>
                <tr>
                    <td>{% trans "First Name" %}</td>
                    <td>{{ object.joint_first_name | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Last Name" %}</td>
                    <td>{{ object.joint_last_name | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Middle Initial" %}</td>
                    <td>{{ object.joint_middle_initial | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Social Security Number / Social Insurance Number" %}</td>
                    <td>{{ object.joint_ssn | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Address" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Line 1" %}</td>
                    <td>{{ object.joint_address_line1 | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Line 2" %}</td>
                    <td>{{ object.joint_address_line2 | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "City" %}</td>
                    <td>{{ object.joint_address_city | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "State" %}</td>
                    <td>{{ object.joint_address_state | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Postal Code" %}</td>
                    <td>{{ object.joint_address_postcode | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Contact" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Cell Phone" %}</td>
                    <td>{{ object.joint_cell_phone | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Employment" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Occupation" %}</td>
                    <td>{{ object.joint_occupation | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Annual Income" %}</td>
                    <td>{{ object.joint_annual_income | currency | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Employer Name" %}</td>
                    <td>{{ object.joint_employer_name | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Time at Employer" %}</td>
                    <td>{{ object.joint_time_at_employer | timeat }}</td>
                </tr>
                <tr>
                    <td>{% trans "Employer Phone" %}</td>
                    <td>{{ object.joint_employer_phone | default:"-" }}</td>
                </tr>

                <tr>
                    <th colspan="2">{% trans "Photo ID" %}</th>
                </tr>
                <tr>
                    <td>{% trans "Photo ID Type" %}</td>
                    <td>{{ object.joint_photo_id_type | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Photo ID Number" %}</td>
                    <td>{{ object.joint_photo_id_number | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Driver's License Province" %}</td>
                    <td>{{ object.joint_drivers_license_province | default:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans "Photo ID Expiration Date" %}</td>
                    <td>{{ object.joint_photo_id_expiration | default:"-" }}</td>
                </tr>
            </table>
        </div>

        <div class="col-md-12">
            <div class="table-header">
                <h2>{% trans "Account Inquiries" %}</h2>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Inquiry Date/Time</th>
                        <th>Inquiry Account Number</th>
                        <th>Status</th>
                        <th>Credit Limit</th>
                        <th>Balance</th>
                        <th>Open to Buy</th>
                        <th>Last Payment Date</th>
                        <th>Last Payment Amount</th>
                        <th>Payment Due Date</th>
                        <th>Payment Due Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for inquiry in object.get_inquiries %}
                        <tr>
                            <td>{{ inquiry.created_datetime }}</td>
                            <td>{{ inquiry.masked_account_number }}</td>
                            <td>{{ inquiry.get_status_display }}</td>
                            <td>{{ inquiry.credit_limit | currency | default:"-" }}</td>
                            <td>{{ inquiry.balance | currency | default:"-" }}</td>
                            <td>{{ inquiry.open_to_buy | currency | default:"-" }}</td>
                            <td>{{ inquiry.last_payment_date | default:"-" }}</td>
                            <td>{{ inquiry.last_payment_amount | currency | default:"-" }}</td>
                            <td>{{ inquiry.payment_due_date | default:"-" }}</td>
                            <td>{{ inquiry.payment_due_amount | currency | default:"-" }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="10">
                                <em>No account inquiries currently exist for this Credit Application</em>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

src/wellsfargo/templates/wfrs/dashboard/application_us_single.html
{% extends 'wfrs/dashboard/application_base.html' %}

{% block main_personal_fields %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_ssn %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_home_phone %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_cell_phone %}
{% endblock %}

{% block main_addr_fields %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_address_state %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_address_postcode %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_time_at_address %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_housing_status %}
{% endblock %}

{% block main_employment_fields %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_occupation %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_employer_name %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_employer_phone %}
    {% include 'dashboard/partials/form_field.html' with field=form.main_time_at_employer %}
{% endblock %}